---
name: test

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: "0 13 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [28.1, snapshot]
    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: cask/setup-cask@master
        with:
          version: snapshot
      - name: Install cask dependencies
        run: cask install
      - name: Run test suite
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "githubactions@github.com"
          make test
